#!/usr/bin/env python3
"""Build docs/done/INDEX.md from docs/done/short/*.md."""

import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

DOCS_ROOT = Path(__file__).parent.parent / "docs"
SHORT_DIR = DOCS_ROOT / "done" / "short"
INDEX_PATH = DOCS_ROOT / "done" / "INDEX.md"

KNOWN_PROJECTS = {"app", "landing", "nginx", "workspace", "cross"}
PROJECT_ORDER = ["app", "landing", "nginx", "workspace", "cross"]

DATE_PREFIX_RE = re.compile(r"^(\d{2})-(\d{2})-(\d{2})-(.+)$")


def parse_frontmatter(text: str) -> Dict[str, str]:
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end == -1:
        return {}
    fm: Dict[str, str] = {}
    for line in text[4:end].splitlines():
        if ":" in line and not line.startswith(" "):
            key, _, val = line.partition(":")
            fm[key.strip()] = val.strip().strip("'\"")
    return fm


def extract_title(text: str) -> Optional[str]:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return None


def parse_filename(stem: str) -> Tuple[Optional[str], Optional[str]]:
    """Return (iso_date, project) parsed from dd-mm-yy-project-slug stem."""
    m = DATE_PREFIX_RE.match(stem)
    if not m:
        return None, None
    day, month, year_short, rest = m.groups()
    iso_date = "20{0}-{1}-{2}".format(year_short, month, day)
    first_part = rest.split("-")[0]
    project = first_part if first_part in KNOWN_PROJECTS else None
    return iso_date, project


def build_index() -> str:
    groups: Dict[str, List[Tuple[str, str, str]]] = {p: [] for p in PROJECT_ORDER}
    archive: List[Tuple[str, str]] = []

    for md_path in sorted(SHORT_DIR.glob("*.md")):
        text = md_path.read_text(encoding="utf-8")
        title = extract_title(text) or md_path.stem
        fm = parse_frontmatter(text)

        iso_date, name_project = parse_filename(md_path.stem)

        project = fm.get("project") or name_project
        date = fm.get("created") or iso_date

        rel_path = "short/{0}".format(md_path.name)

        if date and project and project in KNOWN_PROJECTS:
            groups[project].append((date, title, rel_path))
        else:
            archive.append((title, rel_path))

    lines = [
        "<!-- generated by scripts/build-done-index.py — do not edit -->",
        "# Done index",
        "",
    ]

    for project in PROJECT_ORDER:
        group = groups[project]
        if not group:
            continue
        group.sort(key=lambda e: e[0], reverse=True)
        lines.append("## {0}".format(project))
        for date, title, path in group:
            lines.append("- {0} · [{1}]({2})".format(date, title, path))
        lines.append("")

    if archive:
        lines.append("## archive")
        for title, path in archive:
            lines.append("- [{0}]({1})".format(title, path))
        lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    if not SHORT_DIR.exists():
        print("No docs/done/short/ — nothing to index.")
        sys.exit(0)
    content = build_index()
    INDEX_PATH.write_text(content, encoding="utf-8")
    print("Written {0}".format(INDEX_PATH))
    sys.exit(0)
