#!/usr/bin/env python3
"""Build docs/code-index.md: reverse index mapping code files to tasks that reference them."""

import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple

WORKSPACE_ROOT = Path(__file__).parent.parent
DOCS_ROOT = WORKSPACE_ROOT / "docs"
OUTPUT = DOCS_ROOT / "code-index.md"

SCAN_DIRS = [
    DOCS_ROOT / "backlog",
    DOCS_ROOT / "wip",
    DOCS_ROOT / "done" / "long",
]

SKIP_NAMES = {
    "folder-rules.md",
    "runbook-local.md",
    "runbook-prod.md",
    "INDEX.md",
    "code-index.md",
    "README.md",
}

STATUS_FROM_PATH = {
    "todo": "todo",
    "bugs": "bug",
    "wip": "wip",
    "long": "done",
}


def extract_frontmatter(text: str) -> Optional[Dict]:
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---", 4)
    if end == -1:
        return None
    fm: Dict = {}
    current_list: Optional[str] = None
    for line in text[4:end].splitlines():
        if line.startswith("  - ") and current_list is not None:
            fm[current_list].append(line[4:].strip())
        elif ":" in line and not line.startswith(" "):
            key, _, val = line.partition(":")
            key = key.strip()
            val = val.strip()
            if val in ("", "[]"):
                fm[key] = []
                current_list = key if val == "" else None
            else:
                fm[key] = val.strip("'\"")
                current_list = None
        else:
            current_list = None
    return fm


def extract_title(text: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def status_from_path(md: Path) -> str:
    for part in md.parts:
        if part in STATUS_FROM_PATH:
            return STATUS_FROM_PATH[part]
    return "unknown"


Entry = Tuple[str, str, str]  # (status, slug, title)


def build_index() -> Tuple[Dict[str, List[Entry]], int, int]:
    """Returns (index, total_tasks, tasks_with_related_code)."""
    index: Dict[str, List[Entry]] = defaultdict(list)
    total = 0
    with_code = 0

    for scan_dir in SCAN_DIRS:
        if not scan_dir.exists():
            continue
        for md in sorted(scan_dir.rglob("*.md")):
            if md.name in SKIP_NAMES:
                continue
            text = md.read_text(encoding="utf-8")
            fm = extract_frontmatter(text)
            if fm is None:
                continue

            doc_type = fm.get("type", "")
            if doc_type not in ("task", "bug"):
                continue

            total += 1
            related_code = fm.get("related_code")
            if not related_code or not isinstance(related_code, list):
                continue

            non_empty = [p for p in related_code if p]
            if not non_empty:
                continue

            with_code += 1
            status = fm.get("status") or status_from_path(md)
            slug = md.stem
            title = extract_title(text)

            for code_path in non_empty:
                index[code_path].append((status, slug, title))

    return index, total, with_code


def write_index(index: Dict[str, List[Entry]], total: int, with_code: int) -> None:
    lines: List[str] = []
    lines.append("<!-- generated by scripts/build-code-index.py — do not edit -->")
    lines.append("")
    lines.append("# Code → Tasks Index")
    lines.append("")

    coverage_pct = (with_code / total * 100) if total else 0
    if total == 0 or coverage_pct < 30:
        lines.append(
            "> **Partial coverage** — only {0}/{1} tasks ({2:.0f}%) have a `related_code` field.".format(
                with_code, total, coverage_pct
            )
        )
        lines.append(
            "> Fill `related_code` in task frontmatter so this index is complete."
        )
        lines.append("")

    if not index:
        lines.append("_No tasks with a populated `related_code` field._")
    else:
        for code_path in sorted(index.keys()):
            entries = index[code_path]
            lines.append("### {0}".format(code_path))
            entries.sort(key=lambda e: (e[0], e[1]))
            for status, slug, title in entries:
                title_part = " — «{0}»".format(title) if title else ""
                lines.append("- {0} · {1}{2}".format(status, slug, title_part))
            lines.append("")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        "code-index: {0} code path(s), {1}/{2} tasks with related_code ({3:.0f}%)".format(
            len(index), with_code, total, coverage_pct
        )
    )


def main() -> int:
    if not DOCS_ROOT.exists():
        print("No docs/ directory — nothing to index.")
        return 0
    index, total, with_code = build_index()
    write_index(index, total, with_code)
    return 0


if __name__ == "__main__":
    sys.exit(main())
